-- Emitted by backup workflow via: psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f scripts/dump_functions_triggers.sql
-- Captures function-like objects and triggers for a readable supplemental backup (ordering is not a full topological sort).

\o exports/functions_triggers.sql

\pset tuples_only on
\pset format unaligned

\echo '-- Supplemental backup: functions, aggregates, triggers, event triggers'
\echo '-- Generated by scripts/dump_functions_triggers.sql'
\echo ''

\echo '-- === FUNCTIONS, PROCEDURES, WINDOW FUNCTIONS ==='
SELECT pg_get_functiondef(p.oid) || E';\n'
FROM pg_proc p
JOIN pg_namespace n ON n.oid = p.pronamespace
WHERE p.prokind IN ('f', 'p', 'w')
  AND n.nspname NOT IN ('pg_catalog', 'information_schema')
  AND n.nspname NOT LIKE 'pg_toast%'
  AND n.nspname NOT LIKE 'pg_temp%'
ORDER BY n.nspname, p.proname, p.oid;

\echo '-- === AGGREGATES ==='
SELECT pg_get_aggregatedef(a.oid) || E';\n'
FROM pg_aggregate a
JOIN pg_proc p ON p.oid = a.aggfnoid
JOIN pg_namespace n ON n.oid = p.pronamespace
WHERE n.nspname NOT IN ('pg_catalog', 'information_schema')
  AND n.nspname NOT LIKE 'pg_toast%'
  AND n.nspname NOT LIKE 'pg_temp%'
ORDER BY n.nspname, p.proname, a.oid;

\echo '-- === TRIGGERS (user tables) ==='
SELECT pg_get_triggerdef(t.oid, true) || E';\n'
FROM pg_trigger t
JOIN pg_class c ON c.oid = t.tgrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE NOT t.tgisinternal
  AND n.nspname NOT IN ('pg_catalog', 'information_schema')
  AND n.nspname NOT LIKE 'pg_toast%'
  AND n.nspname NOT LIKE 'pg_temp%'
ORDER BY n.nspname, c.relname, t.tgname;

\echo '-- === EVENT TRIGGERS ==='
SELECT pg_get_event_triggerdef(oid) || E';\n'
FROM pg_event_trigger
ORDER BY evtname;

\o
