\set ON_ERROR_STOP on
\pset tuples_only on
\pset format unaligned

\! mkdir -p exports
\o exports/functions_triggers.sql

SELECT '-- Supplemental backup: functions, aggregates, triggers, event triggers';
SELECT '-- Generated by scripts/dump_functions_triggers.sql';
SELECT '';

-- === FUNCTIONS, PROCEDURES, WINDOW FUNCTIONS ===
SELECT '-- === FUNCTIONS, PROCEDURES, WINDOW FUNCTIONS ===';
SELECT pg_get_functiondef(p.oid) || E'\n'
FROM pg_proc p
JOIN pg_namespace n
  ON n.oid = p.pronamespace
WHERE n.nspname IN ('public', 'auth')
  AND p.prokind IN ('f', 'p', 'w')
ORDER BY n.nspname, p.proname, pg_get_function_identity_arguments(p.oid);

SELECT '';

-- === AGGREGATES ===
SELECT '-- === AGGREGATES (signatures; DDL in schema.sql) ===';
SELECT format('-- %s', p.oid::regprocedure::text) || E'\n'
FROM pg_proc p
JOIN pg_namespace n
  ON n.oid = p.pronamespace
WHERE n.nspname IN ('public', 'auth')
  AND p.prokind = 'a'
ORDER BY n.nspname, p.proname, pg_get_function_identity_arguments(p.oid);

SELECT '';

-- === TRIGGERS ===
SELECT '-- === TRIGGERS ===';
SELECT pg_get_triggerdef(t.oid, true) || E';\n'
FROM pg_trigger t
JOIN pg_class c
  ON c.oid = t.tgrelid
JOIN pg_namespace n
  ON n.oid = c.relnamespace
WHERE n.nspname IN ('public', 'auth')
  AND NOT t.tgisinternal
ORDER BY n.nspname, c.relname, t.tgname;

SELECT '';

-- === EVENT TRIGGERS ===
SELECT '-- === EVENT TRIGGERS ===';
SELECT pg_get_event_triggerdef(e.oid) || E';\n'
FROM pg_event_trigger e
ORDER BY e.evtname;

\o
